/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IReputationSystem__factory } from './IReputationSystem__factory.js';
export { WorldCupBetting__factory } from './WorldCupBetting__factory.js';