/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IReputationSystem, IReputationSystemInterface } from "../../WorldCupBetting.sol/IReputationSystem.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getReputation",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "correct",
        "type": "bool"
      }
    ],
    "name": "updateReputation",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IReputationSystem__factory {
    static readonly abi = _abi;
    static createInterface(): IReputationSystemInterface {
      return new Interface(_abi) as IReputationSystemInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IReputationSystem {
      return new Contract(address, _abi, runner) as unknown as IReputationSystem;
    }
  }
  