/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'IReputationSystem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReputationSystem__factory>
getContractFactory(name: 'PredictionMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PredictionMarket__factory>
getContractFactory(name: 'IReputationSystem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReputationSystem__factory>
getContractFactory(name: 'WorldCupBetting', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.WorldCupBetting__factory>
getContractFactory(name: 'ReputationSystem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ReputationSystem__factory>

  getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'IReputationSystem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReputationSystem>
getContractAt(name: 'PredictionMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PredictionMarket>
getContractAt(name: 'IReputationSystem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReputationSystem>
getContractAt(name: 'WorldCupBetting', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.WorldCupBetting>
getContractAt(name: 'ReputationSystem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ReputationSystem>

  deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'IReputationSystem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationSystem>
deployContract(name: 'PredictionMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionMarket>
deployContract(name: 'IReputationSystem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationSystem>
deployContract(name: 'WorldCupBetting', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WorldCupBetting>
deployContract(name: 'ReputationSystem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationSystem>

  deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'IReputationSystem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationSystem>
deployContract(name: 'PredictionMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionMarket>
deployContract(name: 'IReputationSystem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationSystem>
deployContract(name: 'WorldCupBetting', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WorldCupBetting>
deployContract(name: 'ReputationSystem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationSystem>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  