/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as predictionMarketSol from './PredictionMarket.sol/index.js';
export type { predictionMarketSol };
import type * as worldCupBettingSol from './WorldCupBetting.sol/index.js';
export type { worldCupBettingSol };
export type { MockERC20 } from './MockERC20.js';
export type { ReputationSystem } from './ReputationSystem.js';
export * as factories from './factories/index.js';
export { MockERC20__factory } from './factories/MockERC20__factory.js';
export type { IReputationSystem } from './PredictionMarket.sol/IReputationSystem.js';
export { IReputationSystem__factory } from './factories/PredictionMarket.sol/IReputationSystem__factory.js';
export type { PredictionMarket } from './PredictionMarket.sol/PredictionMarket.js';
export { PredictionMarket__factory } from './factories/PredictionMarket.sol/PredictionMarket__factory.js';
export type { WorldCupBetting } from './WorldCupBetting.sol/WorldCupBetting.js';
export { WorldCupBetting__factory } from './factories/WorldCupBetting.sol/WorldCupBetting__factory.js';
export { ReputationSystem__factory } from './factories/ReputationSystem__factory.js';