/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ReputationSystemInterface extends Interface {
    getFunction(nameOrSignature: "BASE_REPUTATION" | "CORRECT_BONUS" | "INCORRECT_PENALTY" | "MAX_REPUTATION" | "correctBets" | "getReputation" | "getStats" | "getWeight" | "owner" | "predictionMarket" | "renounceOwnership" | "reputation" | "setPredictionMarket" | "totalBets" | "transferOwnership" | "updateReputation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "ReputationUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'BASE_REPUTATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'CORRECT_BONUS', values?: undefined): string;
encodeFunctionData(functionFragment: 'INCORRECT_PENALTY', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_REPUTATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'correctBets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getStats', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getWeight', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'predictionMarket', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPredictionMarket', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalBets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateReputation', values: [AddressLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'BASE_REPUTATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CORRECT_BONUS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'INCORRECT_PENALTY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_REPUTATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'correctBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWeight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictionMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPredictionMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateReputation', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationUpdatedEvent {
      export type InputTuple = [user: AddressLike, newReputation: BigNumberish, correct: boolean];
      export type OutputTuple = [user: string, newReputation: bigint, correct: boolean];
      export interface OutputObject {user: string, newReputation: bigint, correct: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReputationSystem extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReputationSystem;
    waitForDeployment(): Promise<this>;

    interface: ReputationSystemInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASE_REPUTATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CORRECT_BONUS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    INCORRECT_PENALTY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_REPUTATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    correctBets: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getReputation: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getStats: TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {rep: bigint, total: bigint, correct: bigint, accuracy: bigint }],
      'view'
    >
    

    
    getWeight: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    predictionMarket: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reputation: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    setPredictionMarket: TypedContractMethod<
      [_predictionMarket: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalBets: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateReputation: TypedContractMethod<
      [user: AddressLike, correct: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASE_REPUTATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CORRECT_BONUS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'INCORRECT_PENALTY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_REPUTATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'correctBets'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getReputation'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getStats'): TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {rep: bigint, total: bigint, correct: bigint, accuracy: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getWeight'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'predictionMarket'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputation'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setPredictionMarket'): TypedContractMethod<
      [_predictionMarket: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalBets'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateReputation'): TypedContractMethod<
      [user: AddressLike, correct: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ReputationUpdated'): TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ReputationUpdated(address,uint256,bool)': TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
      ReputationUpdated: TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
    
    };
  }