/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IReputationSystem } from './IReputationSystem.js';
export type { PredictionMarket } from './PredictionMarket.js';