/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PredictionMarketInterface extends Interface {
    getFunction(nameOrSignature: "FEE_DENOMINATOR" | "PLATFORM_FEE" | "betCount" | "bets" | "buyPosition" | "calculateShares" | "cancelListing" | "claimWinnings" | "collectedFees" | "createMarket" | "getAvailableFees" | "getMarket" | "getMarketBets" | "getPrice" | "getTotalPool" | "getUserBets" | "listPosition" | "marketBets" | "marketCount" | "markets" | "outcomePools" | "outcomeShares" | "owner" | "placeBet" | "positionPrices" | "positionsForSale" | "renounceOwnership" | "reputationSystem" | "resolveMarket" | "transferOwnership" | "userBets" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BetPlaced" | "FeesWithdrawn" | "MarketCreated" | "MarketResolved" | "OwnershipTransferred" | "PositionListed" | "PositionSold" | "WinningsClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'FEE_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'PLATFORM_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'betCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'bets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyPosition', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateShares', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimWinnings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'collectedFees', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'createMarket', values: [string, string, string[], BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getAvailableFees', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMarketBets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPrice', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTotalPool', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserBets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'listPosition', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketBets', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'markets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'outcomePools', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'outcomeShares', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeBet', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'positionPrices', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'positionsForSale', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reputationSystem', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveMarket', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userBets', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'FEE_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PLATFORM_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'betCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyPosition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimWinnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collectedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAvailableFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarketBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listPosition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outcomePools', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outcomeShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'positionPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'positionsForSale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationSystem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace BetPlacedEvent {
      export type InputTuple = [betId: BigNumberish, marketId: BigNumberish, bettor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [betId: bigint, marketId: bigint, bettor: string, amount: bigint];
      export interface OutputObject {betId: bigint, marketId: bigint, bettor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [token: AddressLike, amount: BigNumberish, to: AddressLike];
      export type OutputTuple = [token: string, amount: bigint, to: string];
      export interface OutputObject {token: string, amount: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketCreatedEvent {
      export type InputTuple = [marketId: BigNumberish, creator: AddressLike, question: string];
      export type OutputTuple = [marketId: bigint, creator: string, question: string];
      export interface OutputObject {marketId: bigint, creator: string, question: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketResolvedEvent {
      export type InputTuple = [marketId: BigNumberish, winningOutcome: BigNumberish];
      export type OutputTuple = [marketId: bigint, winningOutcome: bigint];
      export interface OutputObject {marketId: bigint, winningOutcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PositionListedEvent {
      export type InputTuple = [betId: BigNumberish, price: BigNumberish];
      export type OutputTuple = [betId: bigint, price: bigint];
      export interface OutputObject {betId: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PositionSoldEvent {
      export type InputTuple = [betId: BigNumberish, seller: AddressLike, buyer: AddressLike, price: BigNumberish];
      export type OutputTuple = [betId: bigint, seller: string, buyer: string, price: bigint];
      export interface OutputObject {betId: bigint, seller: string, buyer: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WinningsClaimedEvent {
      export type InputTuple = [betId: BigNumberish, claimer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [betId: bigint, claimer: string, amount: bigint];
      export interface OutputObject {betId: bigint, claimer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PredictionMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): PredictionMarket;
    waitForDeployment(): Promise<this>;

    interface: PredictionMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    FEE_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PLATFORM_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    betCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, bettor: string, marketId: bigint, outcomeIndex: bigint, amount: bigint, shares: bigint, timestamp: bigint, claimed: boolean }],
      'view'
    >
    

    
    buyPosition: TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    calculateShares: TypedContractMethod<
      [_marketId: BigNumberish, _outcomeIndex: BigNumberish, _amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    cancelListing: TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimWinnings: TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    collectedFees: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createMarket: TypedContractMethod<
      [_question: string, _description: string, _outcomes: string[], _resolutionTime: BigNumberish, _arbitrator: AddressLike, _tokenAddress: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    getAvailableFees: TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getMarket: TypedContractMethod<
      [_marketId: BigNumberish, ],
      [[bigint, string, string, string[], bigint, string, string, bigint, bigint, string] & {id: bigint, question: string, description: string, outcomes: string[], resolutionTime: bigint, arbitrator: string, creator: string, status: bigint, totalVolume: bigint, tokenAddress: string }],
      'view'
    >
    

    
    getMarketBets: TypedContractMethod<
      [_marketId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getPrice: TypedContractMethod<
      [_marketId: BigNumberish, _outcomeIndex: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getTotalPool: TypedContractMethod<
      [_marketId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getUserBets: TypedContractMethod<
      [_user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    listPosition: TypedContractMethod<
      [_betId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    marketBets: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    marketCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    markets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, string, bigint, bigint, bigint, string, bigint] & {id: bigint, question: string, description: string, resolutionTime: bigint, arbitrator: string, creator: string, createdAt: bigint, status: bigint, winningOutcome: bigint, tokenAddress: string, totalVolume: bigint }],
      'view'
    >
    

    
    outcomePools: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    outcomeShares: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placeBet: TypedContractMethod<
      [_marketId: BigNumberish, _outcomeIndex: BigNumberish, _amount: BigNumberish, _minShares: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    positionPrices: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    positionsForSale: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reputationSystem: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolveMarket: TypedContractMethod<
      [_marketId: BigNumberish, _winningOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userBets: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    withdrawFees: TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'FEE_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PLATFORM_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'betCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, bettor: string, marketId: bigint, outcomeIndex: bigint, amount: bigint, shares: bigint, timestamp: bigint, claimed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'buyPosition'): TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'calculateShares'): TypedContractMethod<
      [_marketId: BigNumberish, _outcomeIndex: BigNumberish, _amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimWinnings'): TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'collectedFees'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createMarket'): TypedContractMethod<
      [_question: string, _description: string, _outcomes: string[], _resolutionTime: BigNumberish, _arbitrator: AddressLike, _tokenAddress: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAvailableFees'): TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMarket'): TypedContractMethod<
      [_marketId: BigNumberish, ],
      [[bigint, string, string, string[], bigint, string, string, bigint, bigint, string] & {id: bigint, question: string, description: string, outcomes: string[], resolutionTime: bigint, arbitrator: string, creator: string, status: bigint, totalVolume: bigint, tokenAddress: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getMarketBets'): TypedContractMethod<
      [_marketId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPrice'): TypedContractMethod<
      [_marketId: BigNumberish, _outcomeIndex: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalPool'): TypedContractMethod<
      [_marketId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserBets'): TypedContractMethod<
      [_user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'listPosition'): TypedContractMethod<
      [_betId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'marketBets'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'marketCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'markets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, string, bigint, bigint, bigint, string, bigint] & {id: bigint, question: string, description: string, resolutionTime: bigint, arbitrator: string, creator: string, createdAt: bigint, status: bigint, winningOutcome: bigint, tokenAddress: string, totalVolume: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'outcomePools'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'outcomeShares'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placeBet'): TypedContractMethod<
      [_marketId: BigNumberish, _outcomeIndex: BigNumberish, _amount: BigNumberish, _minShares: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'positionPrices'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'positionsForSale'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationSystem'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolveMarket'): TypedContractMethod<
      [_marketId: BigNumberish, _winningOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userBets'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BetPlaced'): TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'MarketCreated'): TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
getEvent(key: 'MarketResolved'): TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PositionListed'): TypedContractEvent<PositionListedEvent.InputTuple, PositionListedEvent.OutputTuple, PositionListedEvent.OutputObject>;
getEvent(key: 'PositionSold'): TypedContractEvent<PositionSoldEvent.InputTuple, PositionSoldEvent.OutputTuple, PositionSoldEvent.OutputObject>;
getEvent(key: 'WinningsClaimed'): TypedContractEvent<WinningsClaimedEvent.InputTuple, WinningsClaimedEvent.OutputTuple, WinningsClaimedEvent.OutputObject>;

    filters: {
      
      'BetPlaced(uint256,uint256,address,uint256)': TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
      BetPlaced: TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256,address)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'MarketCreated(uint256,address,string)': TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
      MarketCreated: TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
    

      'MarketResolved(uint256,uint256)': TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
      MarketResolved: TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PositionListed(uint256,uint256)': TypedContractEvent<PositionListedEvent.InputTuple, PositionListedEvent.OutputTuple, PositionListedEvent.OutputObject>;
      PositionListed: TypedContractEvent<PositionListedEvent.InputTuple, PositionListedEvent.OutputTuple, PositionListedEvent.OutputObject>;
    

      'PositionSold(uint256,address,address,uint256)': TypedContractEvent<PositionSoldEvent.InputTuple, PositionSoldEvent.OutputTuple, PositionSoldEvent.OutputObject>;
      PositionSold: TypedContractEvent<PositionSoldEvent.InputTuple, PositionSoldEvent.OutputTuple, PositionSoldEvent.OutputObject>;
    

      'WinningsClaimed(uint256,address,uint256)': TypedContractEvent<WinningsClaimedEvent.InputTuple, WinningsClaimedEvent.OutputTuple, WinningsClaimedEvent.OutputObject>;
      WinningsClaimed: TypedContractEvent<WinningsClaimedEvent.InputTuple, WinningsClaimedEvent.OutputTuple, WinningsClaimedEvent.OutputObject>;
    
    };
  }