/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as predictionMarketSol from './PredictionMarket.sol/index.js';
export * as worldCupBettingSol from './WorldCupBetting.sol/index.js';
export { MockERC20__factory } from './MockERC20__factory.js';
export { ReputationSystem__factory } from './ReputationSystem__factory.js';