/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface WorldCupBettingInterface extends Interface {
    getFunction(nameOrSignature: "betCount" | "bets" | "buyPosition" | "calculateShares" | "cancelListing" | "claimWinnings" | "collectedFees" | "createMarket" | "getAvailableFees" | "getMarket" | "getMarketBets" | "getPrice" | "getTotalPool" | "getUserBets" | "listPosition" | "marketBets" | "marketCount" | "markets" | "outcomePools" | "outcomeShares" | "owner" | "placeBet" | "positionPrices" | "positionsForSale" | "renounceOwnership" | "reputationSystem" | "resolveMarket" | "transferOwnership" | "userBets" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'betCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'bets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyPosition', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateShares', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimWinnings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'collectedFees', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'createMarket', values: [string, string, string[], BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getAvailableFees', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMarketBets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPrice', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTotalPool', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserBets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'listPosition', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketBets', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'markets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'outcomePools', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'outcomeShares', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeBet', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'positionPrices', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'positionsForSale', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reputationSystem', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveMarket', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userBets', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'betCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyPosition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimWinnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collectedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAvailableFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarketBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listPosition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outcomePools', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outcomeShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'positionPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'positionsForSale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationSystem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface WorldCupBetting extends BaseContract {
    
    connect(runner?: ContractRunner | null): WorldCupBetting;
    waitForDeployment(): Promise<this>;

    interface: WorldCupBettingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    betCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, bettor: string, marketId: bigint, outcomeIndex: bigint, amount: bigint, shares: bigint, timestamp: bigint, claimed: boolean }],
      'view'
    >
    

    
    buyPosition: TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    calculateShares: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    cancelListing: TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimWinnings: TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    collectedFees: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createMarket: TypedContractMethod<
      [_question: string, _description: string, _outcomes: string[], _resolutionTime: BigNumberish, _arbitrator: AddressLike, _tokenAddress: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    getAvailableFees: TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getMarket: TypedContractMethod<
      [_marketId: BigNumberish, ],
      [[bigint, string, string, string[], bigint, string, string, bigint, bigint, string]],
      'view'
    >
    

    
    getMarketBets: TypedContractMethod<
      [_marketId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getPrice: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getTotalPool: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getUserBets: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    listPosition: TypedContractMethod<
      [_betId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    marketBets: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    marketCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    markets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, string, bigint, bigint, bigint, string, bigint] & {id: bigint, question: string, description: string, resolutionTime: bigint, arbitrator: string, creator: string, createdAt: bigint, status: bigint, winningOutcome: bigint, tokenAddress: string, totalVolume: bigint }],
      'view'
    >
    

    
    outcomePools: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    outcomeShares: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placeBet: TypedContractMethod<
      [_marketId: BigNumberish, _outcomeIndex: BigNumberish, _amount: BigNumberish, _minShares: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    positionPrices: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    positionsForSale: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reputationSystem: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolveMarket: TypedContractMethod<
      [_marketId: BigNumberish, _winningOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userBets: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    withdrawFees: TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'betCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, bettor: string, marketId: bigint, outcomeIndex: bigint, amount: bigint, shares: bigint, timestamp: bigint, claimed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'buyPosition'): TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'calculateShares'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimWinnings'): TypedContractMethod<
      [_betId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'collectedFees'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createMarket'): TypedContractMethod<
      [_question: string, _description: string, _outcomes: string[], _resolutionTime: BigNumberish, _arbitrator: AddressLike, _tokenAddress: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAvailableFees'): TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMarket'): TypedContractMethod<
      [_marketId: BigNumberish, ],
      [[bigint, string, string, string[], bigint, string, string, bigint, bigint, string]],
      'view'
    >;
getFunction(nameOrSignature: 'getMarketBets'): TypedContractMethod<
      [_marketId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPrice'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalPool'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserBets'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'listPosition'): TypedContractMethod<
      [_betId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'marketBets'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'marketCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'markets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, string, bigint, bigint, bigint, string, bigint] & {id: bigint, question: string, description: string, resolutionTime: bigint, arbitrator: string, creator: string, createdAt: bigint, status: bigint, winningOutcome: bigint, tokenAddress: string, totalVolume: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'outcomePools'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'outcomeShares'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placeBet'): TypedContractMethod<
      [_marketId: BigNumberish, _outcomeIndex: BigNumberish, _amount: BigNumberish, _minShares: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'positionPrices'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'positionsForSale'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationSystem'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolveMarket'): TypedContractMethod<
      [_marketId: BigNumberish, _winningOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userBets'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [_tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }